#!/bin/bash

NAME="android-src"
source `dirname $0`/common-header

cd /srv/array/exports/android-src

# init
#/home/boj/scripts/google-repo init -u https://android.googlesource.com/platform/manifest

# sync
repo sync >>$LOGFILE 2>&1

source `dirname $0`/common-footer
