#!/bin/bash

if [ -z $NAME ]; then
	exit 1
fi

HOME="/home/boj"
LOCKFILE="$HOME/lock/$NAME"
LOGFILE="$HOME/log/$NAME.log"
SCRIPTDIR="$HOME/scripts"

lockfile -r 0 -l 86400 ${LOCKFILE} >/dev/null 2>&1
if [[ 0 -ne "$?" ]]; then 
    exit 1
fi

echo >>$LOGFILE
echo "===== BEGIN MIRRORS-LAB =====" >>$LOGFILE
date >>$LOGFILE
