#!/bin/bash
# rsync script for mirrors-lab
# for fast rsync only

HOME="/home/boj"
LOGDIR="$HOME/log"
LOCKDIR="$HOME/lock"
DATADIR="/srv/array/exports"

RSYNC_PARAMS="-av --delete --delete-after --address=10.8.95.2"

mirrors=(
	"pypi" "rubygems"
)
sources=(
	"mirrors.tuna.tsinghua.edu.cn::pypi"
	"mirrors.tuna.tsinghua.edu.cn::rubygems"
)

# main script below

len=${#mirrors[@]}
for((i=0;i<len;i++))
do
( # run in subshell
	lockfile="$LOCKDIR/${mirrors[$i]}"
	if [ -f $lockfile ]; then
		exit # exit subshell
	fi

	touch $lockfile

	echo
	echo "===== BEGIN MIRRORS-LAB ====="
	date

	rsync_command="rsync ${RSYNC_PARAMS} ${sources[$i]} $DATADIR/${mirrors[$i]}"
	echo $rsync_command
	$rsync_command

	date
	echo "===== END MIRRORS-LAB ====="

	rm $lockfile

) >>"$LOGDIR/${mirrors[$i]}.log" 2>&1 &
done
