#!/bin/bash

# initialize
# lftp -e "mirror --parallel=10 http://hackage.haskell.org/packages/ /srv/array/exports/hackage/"

# incremental sync
# forked from: http://bitcheese.net/wiki/howto/setup-hackage-mirror

HOME="/home/boj"
LOCKFILE="$HOME/lock/hackage"
LOGFILE="$HOME/log/hackage.log"

if [ -f $LOCKFILE ]; then
	exit
fi

touch $LOCKFILE

echo >>$LOGFILE
echo "===== BEGIN MIRRORS-LAB =====" >>$LOGFILE
date >>$LOGFILE

cd /srv/array/exports/hackage/;

for splitpk in `tar tf 00-index.tar.gz | cut -d/ -f 2,3`; do
	pk=`echo $splitpk | sed 's|/|-|'`
	name=$pk.tar.gz
	if [ ! -a package/$name ]; then
		wget http://hackage.haskell.org/packages/archive/$splitpk/$name -O package/$name
	fi
done

date >>$LOGFILE
echo "===== END MIRRORS-LAB =====" >>$LOGFILE

rm $LOCKFILE
