#!/bin/bash

NAME="hackage"
source common-header

# initialize
# lftp -e "mirror --parallel=10 http://hackage.haskell.org/packages/ /srv/array/exports/hackage/"

# incremental sync
# forked from: http://bitcheese.net/wiki/howto/setup-hackage-mirror

(
echo "Downloading index file..."
cd /srv/array/exports/hackage/
wget -q http://hackage.haskell.org/packages/archive/00-index.tar.gz -O 00-index.tar.gz.tmp
mv 00-index.tar.gz.tmp 00-index.tar.gz

echo "Synchronizing packages..."
for splitpk in `tar tf 00-index.tar.gz | cut -d/ -f 2,3`; do
	pk=`echo $splitpk | sed 's|/|-|'`
	name=$pk.tar.gz
	if [ ! -a archive/$name ]; then
		wget -q http://hackage.haskell.org/packages/archive/$splitpk/$name -O archive/$name.tmp
		mv archive/$name.tmp archive/$name
		echo $name
	fi
done
) >>$LOGFILE 2>&1

source common-footer
