#!/bin/bash
# rsync script for mirrors-lab
# Maintainer: Bojie Li <bojieli@gmail.com>
# Courtesy of Zhang Cheng 2013-05-25

HOME="/home/boj"
LOGDIR="$HOME/log"
LOCKDIR="$HOME/lock"
CONFDIR="$HOME/scripts"
DATADIR="/srv/array/exports"

RSYNC_PARAMS="-av --delete --delete-after --address=10.8.95.2"

while read mirror source param; do
    # validate mirror, source and param
    mirror=${mirror%%[ #]*}   # lines start with ' ' and '#' should be ignored
    [[ -z "$mirror" || -z "$source" ]] && continue
    # do more validate stuff if need

    ( # run in subshell
	# lock timeout 1 day, no retry
	lockfile -r 0 -l 86400 ${LOCKDIR}/${mirror}.lock
    
    	echo
    	echo "===== BEGIN MIRRORS-LAB ====="
    	date
    
    	rsync_command="rsync ${RSYNC_PARAMS} ${param} ${source} ${DATADIR}/${mirror}/"
    	echo $rsync_command
    	$rsync_command
    
    	date
    	echo "===== END MIRRORS-LAB ====="
    
    	rm -f ${LOCKDIR}/${mirror}.lock
    
    ) >>"${LOGDIR}/${mirror}.log" 2>&1 &

done < ${CONFDIR}/mirrors.conf
