#!/bin/bash
# rsync script for mirrors-lab

HOME="/home/boj"
LOGDIR=$HOME/log
LOCKDIR=$HOME/lock
DATADIR=/srv/array/exports

mirrors=(
	"apache" "chakra" "mysql" "gimp" "sagemath"
	"tldp" "postgresql" "pythonxy" "raspbian" "lfs/lfs-website"
	"X" "vim" "rfc" "raspberrypi" "mariadb"
	"mozilla-releases" "trisquel" "kernel.org" "manjaro" "openvz"
	"ruby"
)
sources=(
	"rsync.apache.org::apache-dist"
	"chakra-project.org::chakra"
	"rsync://ftp5.gwdg.de/pub/linux/mysql/"
	"rsync://rsync.mirrorservice.org/ftp.gimp.org/pub/gimp/"
	"rsync.mirrorservice.org::www.sagemath.org"
	"rsync.mirrorservice.org::www.tldp.org"
	"rsync.mirrorservice.org::ftp.postgresql.org"
	"rsync.mirrorservice.org::pythonxy.com"
	"rsync.mirrorservice.org::archive.raspbian.org"
	"linuxfromscratch.org::lfs-website"
	"rsync://rsync.mirrorservice.org/ftp.x.org/pub/"
	"ftp.vim.org::Vim"
	"ftp.vim.org::RFC"
	"ftp.vim.org::raspberrypi"
	"rsync.osuosl.org::mariadb"
	"releases-rsync.mozilla.org::mozilla-releases"
	"rsync.trisquel.info::trisquel.packages"
	"rsync://rsync.kernel.org/pub/"
	"rsync://ftp.rz.tu-bs.de/pub/mirror/manjaro.org/repos/"
	"rsync://download.openvz.org/openvz-download/"
	"rsync://www.mirrorservice.org/ftp.ruby-lang.org/pub/ruby/"
)
params=(
	"--safe-links" "" "" "" ""
	"" "" "" "" ""
	"" "" "" "" "--partial --delay-updates"
	"" "" "" "" ""
	""
)

# main script below

len=${#mirrors[@]}
for((i=0;i<len;i++))
do
( # run in subshell
	lockfile="$LOCKDIR/${mirrors[$i]}"
	if [ -f $lockfile ]; then
		exit # exit subshell
	fi

	touch $lockfile

	echo
	echo "===== BEGIN MIRRORS-LAB ====="
	date

	rsync_command="rsync -av --delete --delete-after ${params[$i]} ${sources[$i]} $DATADIR/${mirrors[$i]}"
	echo $rsync_command
	$rsync_command

	date
	echo "===== END MIRRORS-LAB ====="

	rm $lockfile

) >>"$LOGDIR/${mirrors[$i]}.log" 2>&1 &
done
