#!/bin/bash
# sync script for mirrors-lab
# Maintainer: Bojie Li <bojieli@gmail.com>
# Courtesy of Zhang Cheng 2013-05-25

HOME="/home/boj"
LOGDIR="$HOME/log"
LOCKDIR="$HOME/lock"
DATADIR="/srv/array/exports"

if [[ -z $1 || -z $2 ]]; then
	echo "Usage: sync-script <sync-type> <config-file>"
	exit 1
fi

if [ "$1" == "lftp" ]; then
	COMMAND_HEADER='lftp -e "mirror --delete'
	COMMAND_FOOTER='"'
elif [ "$1" == "rsync" ]; then
	COMMAND_HEADER='rsync -av --delete --delete-after'
	COMMAND_FOOTER=''
else
	echo "unsupported sync command: $1"
	exit 1
fi

CONFIG_FILE=$2
if [[ ! -f "$CONFIG_FILE" ]]; then
	echo "config file $CONFIG_FILE does not exist"
	exit 1
fi

while read mirror source param; do
    # validate mirror, source and param
    mirror=${mirror%%[ #]*}   # lines start with ' ' and '#' should be ignored
    [[ -z "$mirror" || -z "$source" ]] && continue
    # do more validate stuff if need

    ( # run in subshell
	# lock timeout 1 day, no retry
	lockfile -r 0 -l 86400 ${LOCKDIR}/${mirror}.lock >/dev/null 2>&1
	if [[ 0 -ne "$?" ]]; then 
	    exit 1
	fi
    
    	echo
    	echo "===== BEGIN MIRRORS-LAB ====="
    	date
    
    	full_command="${COMMAND_HEADER} ${param} ${source} ${DATADIR}/${mirror}/ ${COMMAND_FOOTER}"
    	echo $full_command
    	eval $full_command
    
    	date
    	echo "===== END MIRRORS-LAB ====="
    
    	rm -f ${LOCKDIR}/${mirror}.lock
    
    ) >>"${LOGDIR}/${mirror}.log" 2>&1 &

done < $CONFIG_FILE
