#!/bin/bash
# sync script for mirrors-lab
# Maintainer: Bojie Li <bojieli@gmail.com>
# Courtesy of Zhang Cheng 2013-05-25

HOME="/home/boj"
LOGDIR="$HOME/log"
LOCKDIR="$HOME/lock"
DATADIR="/srv/array/exports"

if [[ -z $1 || -z $2 ]]; then
	echo "Usage: sync-script <sync-type> <config-file>"
	exit 1
fi

METHOD=$1

CONFIG_FILE=$2
if [[ ! -f "$CONFIG_FILE" ]]; then
	echo "config file $CONFIG_FILE does not exist"
	exit 1
fi

while read mirror source param; do
    # validate mirror, source and param
    mirror=${mirror%%[ #]*}   # lines start with ' ' and '#' should be ignored
    [[ -z "$mirror" || -z "$source" ]] && continue
    # do more validate stuff if need

    ( # run in subshell

	## generate target dirname and sync command
	target=${DATADIR}/${mirror}/
	command=""
	if [ "$METHOD" == "lftp" ]; then
		command="lftp -e 'mirror --delete --parallel=10 ${param} ${source} ${target}'"
	elif [ "$METHOD" == "rsync" ]; then
		command="rsync -av --delete --delete-after ${param} -- ${source} ${target}"
	elif [ "$METHOD" == "git" ]; then
		target=${DATADIR}/git-repos/${mirror}.git
		if [ -f "$target/config" ]; then
			command="GIT_DIR=${target}; git pull"
		else ## initial sync
			command="git clone --mirror -- ${source} ${target}"
		fi
	else
		echo "unsupported sync method $METHOD"
		exit 1
	fi

	## check target directory
	if [ ! -d "$target" ]; then
		echo "$target not exist, creating it"
		mkdir -p $target
		if [ ! -d "$target" ]; then
			exit 1
		fi
	fi

	# lock timeout 1 day, no retry
	lockfile -r 0 -l 86400 ${LOCKDIR}/${mirror}.lock >/dev/null 2>&1
	if [[ 0 -ne "$?" ]]; then 
	    exit 1
	fi
    
    	echo
    	echo "===== BEGIN MIRRORS-LAB ====="
    	date

    	echo $command
    	eval $command
    
    	date
    	echo "===== END MIRRORS-LAB ====="
    
	# remove lock
    	rm -f ${LOCKDIR}/${mirror}.lock
    
    ) >>"${LOGDIR}/${mirror}.log" 2>&1 &

done < $CONFIG_FILE
